#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tap
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting installer/rbac"
    kapp.k14s.io/change-rule.1: "delete before deleting installer/rbac"
    kapp.k14s.io/change-group: "tap/install"
spec:
  packageRef:
    refName: tap.tanzu.vmware.com
    versionSelection:
      constraints: ">=0.0.0"
      prereleases: {}
  serviceAccountName: installer
  values:
  - secretRef:
      name: tap-values
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-values
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting installer/rbac"
    kapp.k14s.io/change-rule.1: "delete before deleting installer/rbac"
type: Opaque
stringData:
  #@yaml/text-templated-strings
  values.yaml: |
    shared:
      ingress_domain: 127.0.0.1
    ceip_policy_disclosed: true
    profile: authoring
    buildservice:
      kp_default_repository: (@= data.values.registry_server @)/(@= data.values.registry_path @)
      kp_default_repository_secret:
        name: tbs-registry
        namespace: tap-install
    supply_chain: testing_scanning
    ootb_supply_chain_testing_scanning:
      registry:
        server: (@= data.values.registry_server @)
        repository: (@= data.values.registry_path @)
      gitops:
        ssh_secret: ""
    namespace_provisioner:
      controller: true
      default_parameters:
        supply_chain_service_account:
          secrets:
          - git
          - oci-store-creds
          imagePullSecrets:
          - oci-store-creds
    cnrs:
      domain_name: 127.0.0.1
    grype:
      namespace: tap-install
    metadata_store:
      ns_for_export_app_cert: '*'
      app_service_type: ClusterIP
    contour:
      infrastructure_provider: vsphere
      envoy:
        service:
          type: NodePort
    excluded_packages:
    - learningcenter.tanzu.vmware.com
    - workshops.learningcenter.tanzu.vmware.com
    - apis.apps.tanzu.vmware.com
    - apiserver.appliveview.tanzu.vmware.com
    - connector.appliveview.tanzu.vmware.com
    - conventions.appliveview.tanzu.vmware.com
    - backend.appliveview.tanzu.vmware.com
    - sso.apps.tanzu.vmware.com
    - bitnami.services.tanzu.vmware.com
    - crossplane.tanzu.vmware.com
    - api-portal.tanzu.vmware.com
    - developer-conventions.tanzu.vmware.com
    - ootb-delivery-basic.tanzu.vmware.com
    - ootb-supply-chain-basic.tanzu.vmware.com
    - ootb-templates.tanzu.vmware.com
    - policy.apps.tanzu.vmware.com
    - spring-boot-conventions.tanzu.vmware
    - local-source-proxy.apps.tanzu.vmware.com
    - cnrs.tanzu.vmware.com
    - tap-gui.tanzu.vmware.com
    - controller.source.apps.tanzu.vmware.com
    tap_telemetry:
      installed_for_vmware_internal_use: "true"
    tekton_pipelines:
      feature_flags:
        enable_api_fields: alpha
        disable_affinity_assistant: "true"