---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting installer/rbac"
    kapp.k14s.io/change-rule.1: "delete before deleting installer/rbac"
    kapp.k14s.io/change-rule.2: "upsert after upserting supplychain/controller"
    kapp.k14s.io/change-rule.3: "delete before deleting supplychain/controller"
    kapp.k14s.io/change-group: "supplychain/component"
  name: conventions-catalog
  namespace: tap-install
spec:
  packageRef:
    refName: conventions.component.apps.tanzu.vmware.com
    versionSelection:
      constraints: ">=0.0.0"
      prereleases: {}
  serviceAccountName: tap-install-sa
  values:
  - secretRef:
      name: conventions-values
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting installer/rbac"
    kapp.k14s.io/change-rule.1: "delete before deleting installer/rbac"
  name: conventions-values
  namespace: tap-install
stringData:
    values.yml: ""
