---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: alm-fetch-tgz-content-oci
spec:
  params:
  - description: location of the input
    name: url
    type: string
  results:
  - name: message
    type: string
  stepTemplate:
    computeResources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1001
      seccompProfile:
        type: RuntimeDefault
  steps:
  - computeResources: {}
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker/
    - name: HOME
      value: /tekton/home/
    image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages@sha256:47c828c51178f178ebb9fb0f56064f40f3382ad4b010c903e40691ff728a04f6
    name: fetch
    script: |
      #!/bin/bash

      set -euox pipefail

      DIR=$(mktemp -d)

      imgpkg pull -i $(params.url) -o $DIR
      if [ $? -ne 0 ]; then
        printf "download failed" | tee $(results.message.path)
        exit 1
      fi

      cp -R $DIR/* $(workspaces.store.path)
      if [ $? -ne 0 ]; then
        printf "copy failed" | tee $(results.message.path)
        exit 1
      fi
  workspaces:
  - description: The store for the content
    name: store