#@ load("@ytt:data", "data")
---
apiVersion: v1
stringData:
  password: #@ data.values.git_password
  username: #@ data.values.git_username
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: https://github.com
  name: git
type: kubernetes.io/basic-auth