---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alm-catalog
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
  name: managed-resource-controller-alm-catalog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alm-catalog
subjects:
#! Giving CRC manager service account admin permissions for now
#! TODO: Remove in the future or use Namespace provisioner instead
- kind: ServiceAccount
  name: managed-resource-controller-manager
  namespace: managed-resource-controller
#! Giving default service account admin permissions for now
#! TODO: Remove in the future or use Namespace provisioner instead
- kind: ServiceAccount
  name: default
  namespace: default