---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin-for-development
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
  name: managed-resource-controller-cluster-admin-for-development
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin-for-development
subjects:
#! Giving MRC manager service account admin permissions for now
#! TODO: Remove in the future or use Namespace provisioner instead
- kind: ServiceAccount
  name: managed-resource-controller-manager
  namespace: managed-resource-controller