---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: git-source
  annotations:
    kapp.k14s.io/change-group: "pipelines"
spec:
  description: Pulls source code using FluxCD GitRepository resource
  params:
  - name: workload-name
    type: string
  - name: git-branch
    type: string
  - name: git-url
    type: string
  # - name: git-commit
  #   type: string
  # - name: git-tag
  #   type: string
  tasks:
    - name: checkout
      params:
      - name: workload-name
        value: $(params.workload-name)
      - name: git-branch
        value: $(params.git-branch)
      - name: git-url
        value: $(params.git-url)
      # - name: git-commit
      #   value: $(params.git-commit)
      # - name: git-tag
      #   value: $(params.git-tag)
      taskSpec:
        params:
        - name: workload-name
        - name: git-branch
        - name: git-url
        # - name: git-commit
        # - name: git-tag
        apiVersion: cartographer.sh/v1alpha1
        kind: ManagedResource
        spec:
          params:
          - name: workload-name
          - name: git-branch
          - name: git-url
          resourceSpec:
            apiVersion: source.toolkit.fluxcd.io/v1beta1
            kind: GitRepository
            metadata:
              name: $(params.workload-name)
            spec:
              interval: 1m0s
              url: $(params.git-url)
              ref: 
                branch: $(params.git-branch)
                # tag: $(params.git-tag)
                # commit: $(params.git-commit)
              ignore: |
                !.git
          resultMappings:
            - name: url
              path: status.artifact.url
            - name: revision
              path: status.artifact.revision
          #! NOTE: HealthRules are required in ManagedResource section
          healthRule:
            multiMatch:
              healthy:
                matchConditions:
                  - status: "True"
                    type: Ready
              unhealthy:
                matchConditions:
                  - status: "False"
                    type: Ready
  results:
    - name: url
      description: url of the resulting source object you can use in your chain
      type: string
      value: $(tasks.checkout.results.url)
    - name: revision
      description: digest of the shipped content sent to 'url'
      type: string
      value: $(tasks.checkout.results.revision)
