apiVersion: tanzu.vmware.com/v1alpha1
kind: AppBuild
metadata:
  name: spring-petclinic
spec:
  gitOps:
    baseBranch: "main"
    subPath: "package_root"
    url: "https://github.com/atmandhol/tap-gitops"
  registry:
    repository: "adhol-playground/supplychain/workload"
    server: "us-east4-docker.pkg.dev"
  source:
    git:
      branch: "main"
      url: "https://github.com/"
    subPath: "source/spring-petclinic"
  build:
    builder:
      kind: "clusterbuilder"
      name: "default"
    serviceAccountName: "default"
  carvel:
    packageName: "spring-petclinic"
    serviceAccountName: "workload-installer"
    packageDomain: "default.tap"
