---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kapp.k14s.io/change-group: "installer/rbac"
  name: installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: installer-cluster-admin-role
subjects:
- kind: ServiceAccount
  name: installer
  namespace: tap-install
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: installer-cluster-admin-role
  annotations:
    kapp.k14s.io/change-group: "installer/rbac"
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kapp.k14s.io/change-group: "installer/rbac"
  name: installer
  namespace: tap-install
