---
apiVersion: supply-chain.apps.tanzu.vmware.com/v1alpha1
kind: Component
metadata:
  name: app-config-server-1.0.0
spec:
  config:
  - path: spec.deployment
    schema:
      description: |
        Configuration for the deployment to be generated
      properties:
        env:
          items:
            description: Environment variables to be added to the app container
            properties:
              name:
                type: string
              value:
                type: string
            type: object
          type: array
        livenessProbe:
          description: If specified, all readiness gates will be evaluated for pod
            liveness.
          properties:
            exec:
              items:
                type: string
              type: array
            failureThreshold:
              type: integer
            grpc:
              properties:
                port:
                  type: integer
                service:
                  type: string
              type: object
            httpGet:
              properties:
                host:
                  type: string
                httpHeaders:
                  items:
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                    type: object
                  type: array
                path:
                  type: string
                port:
                  type: string
                scheme:
                  type: string
              type: object
            initialDelaySeconds:
              type: integer
            periodSeconds:
              type: integer
            successThreshold:
              type: integer
            tcpSocket:
              properties:
                host:
                  type: string
                port:
                  type: string
              type: object
            terminationGracePeriodSeconds:
              type: integer
            timeoutSeconds:
              type: integer
          type: object
        name:
          description: The name of the deployment resource. defaults to workload if
            empty
          type: string
        readinessProbe:
          description: If specified, all readiness gates will be evaluated for pod
            readiness.
          properties:
            exec:
              items:
                type: string
              type: array
            failureThreshold:
              type: integer
            grpc:
              properties:
                port:
                  type: integer
                service:
                  type: string
              type: object
            httpGet:
              properties:
                host:
                  type: string
                httpHeaders:
                  items:
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                    type: object
                  type: array
                path:
                  type: string
                port:
                  type: string
                scheme:
                  type: string
              type: object
            initialDelaySeconds:
              type: integer
            periodSeconds:
              type: integer
            successThreshold:
              type: integer
            tcpSocket:
              properties:
                host:
                  type: string
                port:
                  type: string
              type: object
            terminationGracePeriodSeconds:
              type: integer
            timeoutSeconds:
              type: integer
          type: object
        replicas:
          description: Number of desired pods.
          type: integer
        resources:
          description: Compute Resources required by the app container.
          properties:
            limits:
              description: max limits for CPU and memory
              properties:
                cpu:
                  type: string
                memory:
                  type: string
              type: object
            requests:
              description: min limits for CPU and memory
              properties:
                cpu:
                  type: string
                memory:
                  type: string
              type: object
          type: object
        securityContext:
          description: pod-level security attributes and common container settings
          properties:
            runAsUser:
              type: string
          type: object
        strategy:
          description: DeploymentStrategy describes how to replace existing pods with
            new ones.
          properties:
            rollingUpdate:
              properties:
                maxSurge:
                  type: string
                maxUnavailable:
                  type: string
              type: object
            type:
              type: string
          type: object
      required:
      - replicas
      type: object
  - path: spec.service
    schema:
      description: |
        Configuration for the service to be generated
      properties:
        name:
          description: The name of the ksvc resource. defaults to workload if empty
          type: string
        ports:
          description: The list of ports that are exposed by this service.
          items:
            properties:
              containerport:
                type: string
              name:
                type: string
              port:
                type: integer
            required:
            - containerport
            - port
            - name
            type: object
          type: array
      type: object
  - path: spec.ingress
    schema:
      description: |
        Configuration for the ingress to be generated
      properties:
        clusterIssuer:
          description: the value to used in the annotation cert-manager.io/cluster-issuer
          type: string
        hostname:
          description: hostname is the fully qualified domain name of a network host,
            as defined by RFC 3986
          type: string
        name:
          description: The name of the ingress resource. defaults to workload if empty
          type: string
        port:
          description: provides information about the ports exposed by this LoadBalancer
          type: integer
        tlsSecretName:
          description: secretName is the name of the secret used to terminate TLS
            traffic
          type: string
      type: object
  - path: spec.httpRoute
    schema:
      description: |
        Configuration for the http Route to be generated
      properties:
        gatewayName:
          description: To be used in the httpRoute parentRef
          type: string
        gatewayProtocol:
          description: To be used in the httpRoute parentRef
          type: string
        name:
          description: The name of the httpRoute resource. defaults to workload if
            empty
          type: string
        port:
          description: To be used in the httpRoute BackendRef
          type: integer
      type: object
  - path: spec.registry
    schema:
      description: |
        Configuration for the registry to use
      properties:
        repository:
          description: The name of the repository
          example: my-repository
          type: string
        server:
          description: The name of the registry server, e.g. docker.io
          example: docker.io
          type: string
      required:
      - server
      - repository
      type: object
  description: Generates a server workload template from a config bundle
  inputs:
  - name: conventions
    type: conventions
  outputs:
  - digest: $(pipeline.results.digest)
    name: oci-yaml-files
    type: oci-yaml-files
    url: $(pipeline.results.url)
  - digest: $(pipeline.results.digest-overlay)
    name: oci-ytt-files
    type: oci-ytt-files
    url: $(pipeline.results.url-overlay)
  pipelineRun:
    params:
    - name: config-url
      value: $(inputs.conventions.url)
    - name: workload-name
      value: $(workload.metadata.name)
    - name: workload-labels
      value: $(workload.metadata.labels)
    - name: workload-annotations
      value: $(workload.metadata.annotations)
    - name: ports
      value: $(workload.spec.service.ports)
    - name: deployment
      value: $(workload.spec.deployment)
    - name: service
      value: $(workload.spec.service)
    - name: http-route
      value: $(workload.spec.httpRoute)
    - name: ingress
      value: $(workload.spec.ingress)
    pipelineRef:
      name: app-config-server
    taskRunTemplate:
      podTemplate:
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsUser: 1001
    workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: overlay-data
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi