apiVersion: supply-chain.apps.tanzu.vmware.com/v1alpha1
kind: SupplyChain
metadata:
  name: app.alm.vmware.com-1.0.0
  annotations:
    kapp.k14s.io/change-group: "supplychains"
    kapp.k14s.io/change-rule.0: "upsert after upserting pipelines"
    kapp.k14s.io/change-rule.1: "delete before deleting pipelines"
spec:
  defines:
    group: alm.vmware.com
    kind: App
    plural: apps
    version: v1alpha1
  stages:
  - componentRef:
      name: git-source-1.0.1
    name: source-provider