apiVersion: supply-chain.apps.tanzu.vmware.com/v1alpha1
kind: SupplyChain
metadata:
  name: localcarvelapps.alm.vmware.com-1.0.0
  annotations:
    kapp.k14s.io/change-group: "supplychains"
    kapp.k14s.io/change-rule.0: "upsert after upserting pipelines"
    kapp.k14s.io/change-rule.1: "delete before deleting pipelines"
spec:
  defines:
    group: alm.vmware.com
    kind: LocalCarvelApp
    plural: localcarvelapps
    version: v1alpha1
  stages:
  - componentRef:
      name: tanzu-image-source-1.0.0
    name: source-provider