---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: fetch-tgz-content-oci
  annotations:
    kapp.k14s.io/change-group: "tasks"
spec:
  params:
    - name: url
      type: string
      description: location of the input
  results:
    - name: message
      type: string
  workspaces:
    - name: store
      description: The store for the content
  stepTemplate:
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 1001
      runAsGroup: 1001
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: "RuntimeDefault"
      runAsNonRoot: true
  steps:
    - name: fetch
      image: us-east4-docker.pkg.dev/adhol-playground/image-base/big-base:latest
      script: |
        #!/bin/bash
        
        set -euo pipefail
        
        DIR=$(mktemp -d)
        
        imgpkg pull -i $(params.url) -o $DIR
        if [ $? -ne 0 ]; then
          printf "download failed" | tee $(results.message.path)
          exit 1
        fi
        
        cp -R $DIR/* $(workspaces.store.path)
        if [ $? -ne 0 ]; then
          printf "copy failed" | tee $(results.message.path)
          exit 1
        fi
