---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: store-content-oci
  annotations:
    kapp.k14s.io/change-group: "tasks"
spec:
  workspaces:
    - name: input
      description: The content to be tar'ed and sent
  params:
    - name: workload-name
      type: string
  results:
    - name: digest
      type: string
    - name: url
      type: string
    - name: message
      type: string
  stepTemplate:
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 1001
      runAsGroup: 1001
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: "RuntimeDefault"
      runAsNonRoot: true
  steps:
    - name: store
      image: us-east4-docker.pkg.dev/adhol-playground/image-base/big-base:latest
      env:
        - name: OCI_SERVER
          valueFrom:
            secretKeyRef:
              name: oci-store
              key: server
        - name: OCI_REPOSITORY
          valueFrom:
            secretKeyRef:
              name: oci-store
              key: repository
      script: |
        #!/bin/bash
        
        set -euo pipefail
        
        # FIXME this line is horrible, but I don't (yet) want to write my own binary to do this
        IMAGE_NAME=$(imgpkg push -i ${OCI_SERVER}/${OCI_REPOSITORY}/$(params.workload-name) -f $(workspaces.input.path) --tty | grep Pushed | sed "s/Pushed//" | sed "s/'//g" | sed 's/ //g')
        if [ $? -ne 0 ]; then
          printf "upload failed" | tee $(results.message.path)
          exit 1
        fi
        
        printf "${IMAGE_NAME#*sha256:}" > $(results.digest.path)
        printf "${IMAGE_NAME}" > $(results.url.path)
